services:
  #training:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.cpp
  #  container_name: exgraf_training
  #  networks:
  #    - exgraf_network
  #  depends_on:
  #    - rabbitmq

  metrics_consumer:
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    container_name: exgraf_metrics_consumer
    networks:
      - exgraf_network
    depends_on:
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      RabbitMQ__VirtualHost: "/"
      RabbitMQ__QueueName: metrics

  rabbitmq:
    image: rabbitmq:3-management
    container_name: exgraf_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - exgraf_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  exgraf_network:
    driver: bridge

volumes:
  rabbitmq_data:
