services:
    #training:
    #  build:
    #    context: .
    #    dockerfile: Dockerfile.cpp
    #  container_name: exgraf_training
    #  networks:
    #    - exgraf_network
    #  depends_on:
    #    - rabbitmq

    metrics_consumer:
        build:
            context: .
            dockerfile: Dockerfile.dotnet
        container_name: exgraf_metrics_consumer
        networks:
            - exgraf_network
        depends_on:
            - rabbitmq
            - postgres
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            RabbitMQ__Host: rabbitmq
            RabbitMQ__Username: exgraf
            RabbitMQ__Password: <some_pass>
            RabbitMQ__VirtualHost: "/"
            ConnectionStrings__ModelPerformance: Host=postgres;Port=5432;Database=ModelPerformance;Username=exgraf;Password=<some_pass>

    rabbitmq:
        image: rabbitmq:3-management
        container_name: exgraf_rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - exgraf_network
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=exgraf
            - RABBITMQ_DEFAULT_PASS=<some_pass>
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
            interval: 10s
            timeout: 5s
            retries: 3

    postgres:
        image: postgres:12
        container_name: exgraf_postgres
        ports:
            - "5432:5432"
        networks:
            - exgraf_network
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: exgraf
            POSTGRES_PASSWORD: <some_pass>
            POSTGRES_DB: ModelPerformance

networks:
    exgraf_network:
        driver: bridge

volumes:
    rabbitmq_data:
    postgres_data:
