#include <armadillo>
#include <cstdint>
#include <cstdlib>
#include <fmt/format.h>
#include <memory>
#include <numeric>
#include <optional>
#include <ranges>
#include <span>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/spdlog.h>
#include <stdexcept>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>
