#pragma once

#include <cuda.h>
#include <cuda_runtime.h>
#include <format>
#include <source_location>
#include <stdexcept>
#include <string_view>

#define EXGRAF_LEAK_NAMESPACE
#include "exgraf/logger.hpp"

namespace cuda {

constexpr auto to_string = [](CUresult result) -> std::string_view {
	switch (result) {
	case CUDA_SUCCESS:
		return "CUDA_SUCCESS";
	case CUDA_ERROR_INVALID_VALUE:
		return "CUDA_ERROR_INVALID_VALUE";
	case CUDA_ERROR_OUT_OF_MEMORY:
		return "CUDA_ERROR_OUT_OF_MEMORY";
	case CUDA_ERROR_NOT_INITIALIZED:
		return "CUDA_ERROR_NOT_INITIALIZED";
	case CUDA_ERROR_DEINITIALIZED:
		return "CUDA_ERROR_DEINITIALIZED";
	case CUDA_ERROR_PROFILER_DISABLED:
		return "CUDA_ERROR_PROFILER_DISABLED";
	case CUDA_ERROR_PROFILER_NOT_INITIALIZED:
		return "CUDA_ERROR_PROFILER_NOT_INITIALIZED";
	case CUDA_ERROR_PROFILER_ALREADY_STARTED:
		return "CUDA_ERROR_PROFILER_ALREADY_STARTED";
	case CUDA_ERROR_PROFILER_ALREADY_STOPPED:
		return "CUDA_ERROR_PROFILER_ALREADY_STOPPED";
	case CUDA_ERROR_STUB_LIBRARY:
		return "CUDA_ERROR_STUB_LIBRARY";
	case CUDA_ERROR_DEVICE_UNAVAILABLE:
		return "CUDA_ERROR_DEVICE_UNAVAILABLE";
	case CUDA_ERROR_NO_DEVICE:
		return "CUDA_ERROR_NO_DEVICE";
	case CUDA_ERROR_INVALID_DEVICE:
		return "CUDA_ERROR_INVALID_DEVICE";
	case CUDA_ERROR_DEVICE_NOT_LICENSED:
		return "CUDA_ERROR_DEVICE_NOT_LICENSED";
	case CUDA_ERROR_INVALID_IMAGE:
		return "CUDA_ERROR_INVALID_IMAGE";
	case CUDA_ERROR_INVALID_CONTEXT:
		return "CUDA_ERROR_INVALID_CONTEXT";
	case CUDA_ERROR_CONTEXT_ALREADY_CURRENT:
		return "CUDA_ERROR_CONTEXT_ALREADY_CURRENT";
	case CUDA_ERROR_MAP_FAILED:
		return "CUDA_ERROR_MAP_FAILED";
	case CUDA_ERROR_UNMAP_FAILED:
		return "CUDA_ERROR_UNMAP_FAILED";
	case CUDA_ERROR_ARRAY_IS_MAPPED:
		return "CUDA_ERROR_ARRAY_IS_MAPPED";
	case CUDA_ERROR_ALREADY_MAPPED:
		return "CUDA_ERROR_ALREADY_MAPPED";
	case CUDA_ERROR_NO_BINARY_FOR_GPU:
		return "CUDA_ERROR_NO_BINARY_FOR_GPU";
	case CUDA_ERROR_ALREADY_ACQUIRED:
		return "CUDA_ERROR_ALREADY_ACQUIRED";
	case CUDA_ERROR_NOT_MAPPED:
		return "CUDA_ERROR_NOT_MAPPED";
	case CUDA_ERROR_NOT_MAPPED_AS_ARRAY:
		return "CUDA_ERROR_NOT_MAPPED_AS_ARRAY";
	case CUDA_ERROR_NOT_MAPPED_AS_POINTER:
		return "CUDA_ERROR_NOT_MAPPED_AS_POINTER";
	case CUDA_ERROR_ECC_UNCORRECTABLE:
		return "CUDA_ERROR_ECC_UNCORRECTABLE";
	case CUDA_ERROR_UNSUPPORTED_LIMIT:
		return "CUDA_ERROR_UNSUPPORTED_LIMIT";
	case CUDA_ERROR_CONTEXT_ALREADY_IN_USE:
		return "CUDA_ERROR_CONTEXT_ALREADY_IN_USE";
	case CUDA_ERROR_PEER_ACCESS_UNSUPPORTED:
		return "CUDA_ERROR_PEER_ACCESS_UNSUPPORTED";
	case CUDA_ERROR_INVALID_PTX:
		return "CUDA_ERROR_INVALID_PTX";
	case CUDA_ERROR_INVALID_GRAPHICS_CONTEXT:
		return "CUDA_ERROR_INVALID_GRAPHICS_CONTEXT";
	case CUDA_ERROR_NVLINK_UNCORRECTABLE:
		return "CUDA_ERROR_NVLINK_UNCORRECTABLE";
	case CUDA_ERROR_JIT_COMPILER_NOT_FOUND:
		return "CUDA_ERROR_JIT_COMPILER_NOT_FOUND";
	case CUDA_ERROR_UNSUPPORTED_PTX_VERSION:
		return "CUDA_ERROR_UNSUPPORTED_PTX_VERSION";
	case CUDA_ERROR_JIT_COMPILATION_DISABLED:
		return "CUDA_ERROR_JIT_COMPILATION_DISABLED";
	case CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY:
		return "CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY";
	case CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC:
		return "CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC";
	case CUDA_ERROR_CONTAINED:
		return "CUDA_ERROR_CONTAINED";
	case CUDA_ERROR_INVALID_SOURCE:
		return "CUDA_ERROR_INVALID_SOURCE";
	case CUDA_ERROR_FILE_NOT_FOUND:
		return "CUDA_ERROR_FILE_NOT_FOUND";
	case CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND:
		return "CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND";
	case CUDA_ERROR_SHARED_OBJECT_INIT_FAILED:
		return "CUDA_ERROR_SHARED_OBJECT_INIT_FAILED";
	case CUDA_ERROR_OPERATING_SYSTEM:
		return "CUDA_ERROR_OPERATING_SYSTEM";
	case CUDA_ERROR_INVALID_HANDLE:
		return "CUDA_ERROR_INVALID_HANDLE";
	case CUDA_ERROR_ILLEGAL_STATE:
		return "CUDA_ERROR_ILLEGAL_STATE";
	case CUDA_ERROR_LOSSY_QUERY:
		return "CUDA_ERROR_LOSSY_QUERY";
	case CUDA_ERROR_NOT_FOUND:
		return "CUDA_ERROR_NOT_FOUND";
	case CUDA_ERROR_NOT_READY:
		return "CUDA_ERROR_NOT_READY";
	case CUDA_ERROR_ILLEGAL_ADDRESS:
		return "CUDA_ERROR_ILLEGAL_ADDRESS";
	case CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES:
		return "CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES";
	case CUDA_ERROR_LAUNCH_TIMEOUT:
		return "CUDA_ERROR_LAUNCH_TIMEOUT";
	case CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING:
		return "CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING";
	case CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED:
		return "CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED";
	case CUDA_ERROR_PEER_ACCESS_NOT_ENABLED:
		return "CUDA_ERROR_PEER_ACCESS_NOT_ENABLED";
	case CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE:
		return "CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE";
	case CUDA_ERROR_CONTEXT_IS_DESTROYED:
		return "CUDA_ERROR_CONTEXT_IS_DESTROYED";
	case CUDA_ERROR_ASSERT:
		return "CUDA_ERROR_ASSERT";
	case CUDA_ERROR_TOO_MANY_PEERS:
		return "CUDA_ERROR_TOO_MANY_PEERS";
	case CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED:
		return "CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED";
	case CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED:
		return "CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED";
	case CUDA_ERROR_HARDWARE_STACK_ERROR:
		return "CUDA_ERROR_HARDWARE_STACK_ERROR";
	case CUDA_ERROR_ILLEGAL_INSTRUCTION:
		return "CUDA_ERROR_ILLEGAL_INSTRUCTION";
	case CUDA_ERROR_MISALIGNED_ADDRESS:
		return "CUDA_ERROR_MISALIGNED_ADDRESS";
	case CUDA_ERROR_INVALID_ADDRESS_SPACE:
		return "CUDA_ERROR_INVALID_ADDRESS_SPACE";
	case CUDA_ERROR_INVALID_PC:
		return "CUDA_ERROR_INVALID_PC";
	case CUDA_ERROR_LAUNCH_FAILED:
		return "CUDA_ERROR_LAUNCH_FAILED";
	case CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE:
		return "CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE";
	case CUDA_ERROR_TENSOR_MEMORY_LEAK:
		return "CUDA_ERROR_TENSOR_MEMORY_LEAK";
	case CUDA_ERROR_NOT_PERMITTED:
		return "CUDA_ERROR_NOT_PERMITTED";
	case CUDA_ERROR_NOT_SUPPORTED:
		return "CUDA_ERROR_NOT_SUPPORTED";
	case CUDA_ERROR_SYSTEM_NOT_READY:
		return "CUDA_ERROR_SYSTEM_NOT_READY";
	case CUDA_ERROR_SYSTEM_DRIVER_MISMATCH:
		return "CUDA_ERROR_SYSTEM_DRIVER_MISMATCH";
	case CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE:
		return "CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE";
	case CUDA_ERROR_MPS_CONNECTION_FAILED:
		return "CUDA_ERROR_MPS_CONNECTION_FAILED";
	case CUDA_ERROR_MPS_RPC_FAILURE:
		return "CUDA_ERROR_MPS_RPC_FAILURE";
	case CUDA_ERROR_MPS_SERVER_NOT_READY:
		return "CUDA_ERROR_MPS_SERVER_NOT_READY";
	case CUDA_ERROR_MPS_MAX_CLIENTS_REACHED:
		return "CUDA_ERROR_MPS_MAX_CLIENTS_REACHED";
	case CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED:
		return "CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED";
	case CUDA_ERROR_MPS_CLIENT_TERMINATED:
		return "CUDA_ERROR_MPS_CLIENT_TERMINATED";
	case CUDA_ERROR_CDP_NOT_SUPPORTED:
		return "CUDA_ERROR_CDP_NOT_SUPPORTED";
	case CUDA_ERROR_CDP_VERSION_MISMATCH:
		return "CUDA_ERROR_CDP_VERSION_MISMATCH";
	case CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED:
		return "CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED";
	case CUDA_ERROR_STREAM_CAPTURE_INVALIDATED:
		return "CUDA_ERROR_STREAM_CAPTURE_INVALIDATED";
	case CUDA_ERROR_STREAM_CAPTURE_MERGE:
		return "CUDA_ERROR_STREAM_CAPTURE_MERGE";
	case CUDA_ERROR_STREAM_CAPTURE_UNMATCHED:
		return "CUDA_ERROR_STREAM_CAPTURE_UNMATCHED";
	case CUDA_ERROR_STREAM_CAPTURE_UNJOINED:
		return "CUDA_ERROR_STREAM_CAPTURE_UNJOINED";
	case CUDA_ERROR_STREAM_CAPTURE_ISOLATION:
		return "CUDA_ERROR_STREAM_CAPTURE_ISOLATION";
	case CUDA_ERROR_STREAM_CAPTURE_IMPLICIT:
		return "CUDA_ERROR_STREAM_CAPTURE_IMPLICIT";
	case CUDA_ERROR_CAPTURED_EVENT:
		return "CUDA_ERROR_CAPTURED_EVENT";
	case CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD:
		return "CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD";
	case CUDA_ERROR_TIMEOUT:
		return "CUDA_ERROR_TIMEOUT";
	case CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE:
		return "CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE";
	case CUDA_ERROR_EXTERNAL_DEVICE:
		return "CUDA_ERROR_EXTERNAL_DEVICE";
	case CUDA_ERROR_INVALID_CLUSTER_SIZE:
		return "CUDA_ERROR_INVALID_CLUSTER_SIZE";
	case CUDA_ERROR_FUNCTION_NOT_LOADED:
		return "CUDA_ERROR_FUNCTION_NOT_LOADED";
	case CUDA_ERROR_INVALID_RESOURCE_TYPE:
		return "CUDA_ERROR_INVALID_RESOURCE_TYPE";
	case CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION:
		return "CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION";
	case CUDA_ERROR_KEY_ROTATION:
		return "CUDA_ERROR_KEY_ROTATION";
	case CUDA_ERROR_UNKNOWN:
		return "CUDA_ERROR_UNKNOWN";
	default:
		return "UNKNOWN_CUDA_ERROR";
	}
};

inline auto check_cuda_error(
		CUresult result,
		const std::source_location location = std::source_location::current()) {
	if (result != CUDA_SUCCESS) {
		auto error_string = to_string(result);
		info("CUDA error: {}", error_string);
		throw std::runtime_error(
				std::format("CUDA error at {}:{} ({}): {}", location.file_name(),
										location.line(), location.function_name(), error_string));
	}
}

inline auto check_cuda_driver_error(
		CUresult result,
		const std::source_location location = std::source_location::current()) {
	if (result != CUDA_SUCCESS) {
		const char *error_name;
		const char *error_string;
		cuGetErrorName(result, &error_name);
		cuGetErrorString(result, &error_string);
		error("CUDA driver error {} ({}) at {}:{}: {}", to_string(result),
					error_name, location.file_name(), location.line(), error_string);
		throw std::runtime_error(
				std::format("CUDA driver error at {}:{} ({}): {}", location.file_name(),
										location.line(), location.function_name(), error_string));
	}
}

template <typename T> struct DeviceAllocatable {
	static constexpr auto Size = sizeof(T);
	static auto size(const T &) { return static_cast<std::size_t>(sizeof(T)); }
	static auto as_span(const T &s) -> std::span<const T> = delete;
};

template <typename T> struct DeviceAllocatable<arma::Mat<T>> {
	static auto size(const arma::Mat<T> &t) {
		const auto size = t.size() * sizeof(T);
		return static_cast<std::size_t>(size);
	}
	static auto as_span(const arma::Mat<T> &s) -> std::span<const T> {
		return {s.memptr(), s.n_elem};
	}
};

template <typename T>
concept HasStaticSize = requires {
	{ DeviceAllocatable<T>::S } -> std::same_as<std::size_t>;
};

#define MakeNonCopyNonMove(Class)                                              \
	Class(const Class &) = delete;                                               \
	Class &operator=(const Class &) = delete;                                    \
	Class(Class &&) = delete;                                                    \
	Class &operator=(Class &&) = delete

} // namespace cuda

#define CUDA_CHECK(call) cuda::check_cuda_error((call))
#define CUDA_DRIVER_CHECK(call) cuda::check_cuda_driver_error((call))
